name: myfirst-action
on: workflow_dispatch
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Print "Greetings"
      run: echo "Hello, ${{ vars.MY_NAME }}"
    - name: Print "Cogratulations"
      run: echo "From Accenture"
